#ifndef CONSTANTS_H
#define CONSTANTS_H

#define GAME_TICKRATE 500
#define MAX_ENTITIES 1500
#define MAX_PARTICLES 100
#define MAX_ACTIVE_POWERUPS 10

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define ZONE_COUNT 2

#define EXPLOSIVE_ASTEROID_BULLETS 30

#define MAX_OVERHEAT 100

#define SPRITE_SCALE 4

#define NORMAL_SPEED 500
#define BOOST_SPEED 600

#define NORMAL_FIREDELAY 6
#define BOOST_FIREDELAY 3

#endif // CONSTANTS_H