#ifndef CONSTANTS_H
#define CONSTANTS_H

#define GAME_TICKRATE 500
#define MAX_ENTITIES 1500
#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define ZONE_COUNT 2

#define EXPLOSIVE_ASTEROID_BULLETS 30

#define NORMAL_BULLET_DMG 2
#define ENEMY_BULLET_DMG 10

#define MAX_OVERHEAT 100

#define SPRITE_SCALE 4

#endif // CONSTANTS_H